/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R9PlayersRouteImport } from './routes/9-players'
import { Route as R8PlayersMixedRouteImport } from './routes/8-players-mixed'
import { Route as R8PlayersRouteImport } from './routes/8-players'
import { Route as R16PlayersRouteImport } from './routes/16-players'
import { Route as R12PlayersMixedRouteImport } from './routes/12-players-mixed'
import { Route as R12PlayersRouteImport } from './routes/12-players'
import { Route as IndexRouteImport } from './routes/index'

const R9PlayersRoute = R9PlayersRouteImport.update({
  id: '/9-players',
  path: '/9-players',
  getParentRoute: () => rootRouteImport,
} as any)
const R8PlayersMixedRoute = R8PlayersMixedRouteImport.update({
  id: '/8-players-mixed',
  path: '/8-players-mixed',
  getParentRoute: () => rootRouteImport,
} as any)
const R8PlayersRoute = R8PlayersRouteImport.update({
  id: '/8-players',
  path: '/8-players',
  getParentRoute: () => rootRouteImport,
} as any)
const R16PlayersRoute = R16PlayersRouteImport.update({
  id: '/16-players',
  path: '/16-players',
  getParentRoute: () => rootRouteImport,
} as any)
const R12PlayersMixedRoute = R12PlayersMixedRouteImport.update({
  id: '/12-players-mixed',
  path: '/12-players-mixed',
  getParentRoute: () => rootRouteImport,
} as any)
const R12PlayersRoute = R12PlayersRouteImport.update({
  id: '/12-players',
  path: '/12-players',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/12-players': typeof R12PlayersRoute
  '/12-players-mixed': typeof R12PlayersMixedRoute
  '/16-players': typeof R16PlayersRoute
  '/8-players': typeof R8PlayersRoute
  '/8-players-mixed': typeof R8PlayersMixedRoute
  '/9-players': typeof R9PlayersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/12-players': typeof R12PlayersRoute
  '/12-players-mixed': typeof R12PlayersMixedRoute
  '/16-players': typeof R16PlayersRoute
  '/8-players': typeof R8PlayersRoute
  '/8-players-mixed': typeof R8PlayersMixedRoute
  '/9-players': typeof R9PlayersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/12-players': typeof R12PlayersRoute
  '/12-players-mixed': typeof R12PlayersMixedRoute
  '/16-players': typeof R16PlayersRoute
  '/8-players': typeof R8PlayersRoute
  '/8-players-mixed': typeof R8PlayersMixedRoute
  '/9-players': typeof R9PlayersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/12-players'
    | '/12-players-mixed'
    | '/16-players'
    | '/8-players'
    | '/8-players-mixed'
    | '/9-players'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/12-players'
    | '/12-players-mixed'
    | '/16-players'
    | '/8-players'
    | '/8-players-mixed'
    | '/9-players'
  id:
    | '__root__'
    | '/'
    | '/12-players'
    | '/12-players-mixed'
    | '/16-players'
    | '/8-players'
    | '/8-players-mixed'
    | '/9-players'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R12PlayersRoute: typeof R12PlayersRoute
  R12PlayersMixedRoute: typeof R12PlayersMixedRoute
  R16PlayersRoute: typeof R16PlayersRoute
  R8PlayersRoute: typeof R8PlayersRoute
  R8PlayersMixedRoute: typeof R8PlayersMixedRoute
  R9PlayersRoute: typeof R9PlayersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/9-players': {
      id: '/9-players'
      path: '/9-players'
      fullPath: '/9-players'
      preLoaderRoute: typeof R9PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/8-players-mixed': {
      id: '/8-players-mixed'
      path: '/8-players-mixed'
      fullPath: '/8-players-mixed'
      preLoaderRoute: typeof R8PlayersMixedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/8-players': {
      id: '/8-players'
      path: '/8-players'
      fullPath: '/8-players'
      preLoaderRoute: typeof R8PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/16-players': {
      id: '/16-players'
      path: '/16-players'
      fullPath: '/16-players'
      preLoaderRoute: typeof R16PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/12-players-mixed': {
      id: '/12-players-mixed'
      path: '/12-players-mixed'
      fullPath: '/12-players-mixed'
      preLoaderRoute: typeof R12PlayersMixedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/12-players': {
      id: '/12-players'
      path: '/12-players'
      fullPath: '/12-players'
      preLoaderRoute: typeof R12PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R12PlayersRoute: R12PlayersRoute,
  R12PlayersMixedRoute: R12PlayersMixedRoute,
  R16PlayersRoute: R16PlayersRoute,
  R8PlayersRoute: R8PlayersRoute,
  R8PlayersMixedRoute: R8PlayersMixedRoute,
  R9PlayersRoute: R9PlayersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
