name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch name if different

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust to your Node version
          cache: 'npm'  # Change to 'yarn' or 'pnpm' if you use those

      - name: Install dependencies
        run: npm ci  # Use 'yarn install --frozen-lockfile' for yarn or 'pnpm install --frozen-lockfile' for pnpm

      - name: Build
        run: npm run build  # Adjust if your build command is different

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust if your build output directory is different
          publish_branch: gh-pages  # The branch where the built site will be deployed